package enums;

import models.cards.Card;

public enum Origin {
    FIRSTPLAYER_CLOSECOMBAT(),
    FIRSTPLAYER_RANGED(),
    FIRSTPLAYER_SIEGE(),
    SECONDPLAYER_CLOSECOMBAT(),
    SECONDPLAYER_RANGED(),
    SECONDPLAYER_SIEGE(),
    FIRSTPLAYER_INPLAY(),
    SECONDPLAYER_INPLAY(),
    FIRSTPLAYER_DECK(),
    SECONDPLAYER_DECK(),
    FIRSTPLATER_DEAD(),
    SECONDPLAYER_DEAD(),
    WEATHER(),
    NULL()
    ;
}
